version: "3.8"

networks:
  ea-services: {}

services:

  rabbitmq:
    image: rabbitmq:3-management
    hostname: message-broker
    networks:
      - ea-services
    ports:
      - "5674:5672"
      - "15672:15672" # Admin UI (http://localhost:15672  .. admin:admin)
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin

  mysql:
    image: mysql
    networks:
      - ea-services
    environment:
      MYSQL_DATABASE: "alumni-db"
      MYSQL_ROOT_PASSWORD: "developer"
      MYSQL_ROOT_HOST: "%"
      MYSQL_TCP_PORT: "3307"
    ports:
      - "3307:3307"
    expose:
      - "3307"

  registry:
    image: dinomov/discovery-service
    ports:
      - "8761:8761"
    networks:
      - ea-services

  config:
    image: dinomov/configuration-service
    networks:
      - ea-services
    depends_on:
      - registry
    restart: always
    ports:
      - "9296:9296"

  gateway:
    image: dinomov/api-gateway
    networks:
      - ea-services
    depends_on:
      - registry
    restart: always
    ports:
      - "8080:8080"

  event-service:
    image: dinomov/event-service
    networks:
      - ea-services
    depends_on:
      - config
      - registry
      - mysql
    restart: always
    ports:
      - "9901:9901"

  job-service:
    image: dinomov/job-service
    networks:
      - ea-services
    depends_on:
      - config
      - registry
      - mysql
    restart: always
    ports:
      - "9991:9991"

  news-service:
    image: dinomov/news-service
    networks:
      - ea-services
    depends_on:
      - config
      - registry
      - mysql
    restart: always
    ports:
      - "9919:9919"

  survey-service:
    image: dinomov/survey-service
    networks:
      - ea-services
    depends_on:
      - config
      - registry
      - mysql
    restart: always
    ports:
      - "8083:8083"

  user-service:
    image: dinomov/user-service
    networks:
      - ea-services
    depends_on:
      - config
      - registry
      - mysql
    restart: always
    ports:
      - "9001:9001"