version: "3.8"

services:

  rabbitmq:
    image: rabbitmq:3-management
    hostname: message-broker
    ports:
      - "5672:5672"
      - "15672:15672" # Admin UI (http://localhost:15672  .. admin:admin)
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin

  mysql:
    image: mysql:5.7.18
    # Set max_allowed_packet to 512M for provisioning
    command: --max-allowed-packet=512M --performance-schema=FALSE --transaction-isolation=READ-COMMITTED --init-connect='SET collation_connection=utf8_bin' --init-connect='SET NAMES utf8;' --character-set-server=utf8 --collation-server=utf8_bin --lower-case-table-names=2 --max-connections=500
    container_name: demo_mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3307:3306"

  registry:
    image: dinomov/discovery-service
    ports:
      - "8761:8761"

  config:
    image: dinomov/configuration-service
    depends_on:
      - registry
    restart: always
    ports:
      - "9296:9296"

  gateway:
    image: dinomov/api-gateway
    depends_on:
      - registry
    restart: always
    ports:
      - "8080:8080"

  event-service:
    image: dinomov/event-service
    depends_on:
      - registry
      - mysql
    restart: always
    ports:
      - "9901:9901"

  job-service:
    image: dinomov/job-service
    depends_on:
      - registry
      - mysql
    restart: always
    ports:
      - "9991:9991"

  news-service:
    image: dinomov/news-service
    depends_on:
      - registry
      - mysql
    restart: always
    ports:
      - "9919:9919"

  user-service:
    image: dinomov/user-service
    depends_on:
      - registry
      - mysql
    restart: always
    ports:
      - "9001:9001"