spring:
  application:
    name: api-gateway
    cloud:
      gateway:
        discovery:
          locator:
            enabled: true
        routes:
          - id: auth-service
            uri: lb://user-service
            predicates:
              - Path=/uaa/**

          - id: admin-service
            uri: lb://user-service
            predicates:
              - Path=/admin/**
            filters:
              - RoleAuth=ADMIN


jwt:
  secret: MiAVzqUXy5Tfr1kVIGpPMiAVzqUXy5Tfr1kVIGpP

